config/routes.rb
Rails.application.routes.draw do
  resources :topics

  resources :subjects

  resources :tests

  resources :users

  root 'tests#index'

  get 'login'=>'sessions#new', as: :login
  post 'login'=>'sessions#create'
  get 'logout'=>'sessions#destroy', as: :logout

  post "markdown/preview"
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  validates :name, presence: true
  belongs_to :subject
  has_many :tests,->{order("name ASC")}, dependent: :destroy

  attr_reader :test_topic

  scope :ordering, ->{order(:name)}

  def private?
    self.groups.size == 0
  end


  def edit?(u)
    u && u.admin?
  end

  def self.add?(u)
    u && u.admin?
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic, only: [:show, :edit, :update, :destroy]

  # GET /topics
  # GET /topics.json
  def index
    # @topics = Topic.all
    respond_to do |format|
      format.html { @topics = Topic.ordering.page(params[:page]) }
      format.json do
        @topics = Topic.ordering.where("upper(name) like upper(:q)", q: "%#{params[:q]}%").all
        render json: @topics
      end
    end
  end

  # GET /topics/1
  # GET /topics/1.json
  def show
  end

  # GET /topics/new
  def new
    @topic = Topic.new
  end

  # GET /topics/1/edit
  def edit
  end

  # POST /topics
  # POST /topics.json
  def create
    @topic = Topic.new(topic_params)

    respond_to do |format|
      if @topic.save
        format.html { redirect_to @topic, notice: 'Тема была успешно создана.' }
        format.json { render :show, status: :created, location: @topic }
      else
        format.html { render :new }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /topics/1
  # PATCH/PUT /topics/1.json
  def update
    respond_to do |format|
      if @topic.update(topic_params)
        format.html { redirect_to @topic, notice: 'Тема была успешно изменена.' }
        format.json { render :show, status: :ok, location: @topic }
      else
        format.html { render :edit }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /topics/1
  # DELETE /topics/1.json
  def destroy
    @topic.destroy
    respond_to do |format|
      format.html { redirect_to topics_url, notice: 'Тема была успешно удалена.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_topic
      @topic = Topic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def topic_params
      params.require(:topic).permit(:name)
    end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_form.html.haml
-#= form_for @topic do |f|
-#  - if @topic.errors.any?
-#    #error_explanation
-#      %h2= "#{pluralize(@topic.errors.count, "error")} prohibited this topic from being saved:"
-#      %ul
-#        - @topic.errors.full_messages.each do |msg|
-#          %li= msg
-#
-#  .field
-#    = f.label :name
-#    = f.text_field :name
-#  .actions
-#    = f.submit 'Save'



-if session[:user] != 'stud1' and session[:user] != 'stud2'
  = form_for @topic do |f|
    =error_messages_for @topic
    .form-group
      =f.label :name
      =f.text_field :name, class: 'form-control'
    .form-group
      = f.label :subject_id
      = f.select :subject_id, Subject.all.map{|c| [c.name, c.id]},{}

    -#%li{class: ('active' if controller_name=='genres')}=link_to "Жанры",markdown_preview_url

    .form-actions
    = f.submit nil, class: 'btn btn-primary'
-else
  %h1
    Не доступно

app/views/topics/edit.html.haml
%h1 Редактирование темы

= render 'form'

= link_to 'Просмотр', @topic,class: 'btn btn-primary'
\|
= link_to 'Назад', topics_path,class: 'btn btn-primary'

app/views/topics/index.html.haml
-#%h1 Listing topics
-#
-#%table
-#  %tr
-#    %th Name
-#    %th
-#    %th
-#    %th
-#
-#  - @topics.each do |topic|
-#    %tr
-#      %td= topic.name
-#      %td= link_to 'Show', topic
-#      %td= link_to 'Edit', edit_topic_path(topic)
-#      %td= link_to 'Destroy', topic, :method => :delete, :data => { :confirm => 'Are you sure?' }
-#
-#%br
-#
-#= link_to 'New Topic', new_topic_path



%h1 Список тем

%table.table
  %tr
    %th= Topic.human_attribute_name(:name)
    %th
    %th
    %th

  - @topics.each do |topic|
    %tr
      %td= topic.name
      %td
        = link_to 'Показать', topic
      %td
        -if session[:user] == 'tutor'
          = link_to 'Изменить', edit_topic_path(topic)
      %td
        -if session[:user] == 'tutor'
          = link_to 'Удалить', topic, :method => :delete, :data => { :confirm => 'Вы уверены?' }

%br

-if session[:user] == 'tutor'
  = link_to 'Добавить тему', new_topic_path

app/views/topics/new.html.haml
%h1 Новая тема

= render 'form'

= link_to 'Назад', topics_path,class: 'btn btn-primary'

app/views/topics/show.html.haml
%p#notice= notice

%p
  %b name:
  = @topic.name

= link_to 'Редактирование', edit_topic_path(@topic),class: 'btn btn-primary'
\|
= link_to 'Назад', topics_path,class: 'btn btn-primary'