config/routes.rb
Rails.application.routes.draw do
  resources :topics

  resources :subjects

  resources :tests

  resources :users

  root 'tests#index'

  get 'login'=>'sessions#new', as: :login
  post 'login'=>'sessions#create'
  get 'logout'=>'sessions#destroy', as: :logout

  post "markdown/preview"
end

app/models/subject.rb
class Subject < ActiveRecord::Base
  validates :name, presence: true
  has_many :topics,->{order("name ASC")}, dependent: :destroy
  attr_reader :test_topic

  def private?
    self.groups.size == 0
  end


  def edit?(u)
    u && u.admin?
  end

  def self.add?(u)
    u && u.admin?
  end
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  before_action :set_subject, only: [:show, :edit, :update, :destroy]

  # GET /subjects
  # GET /subjects.json
  def index
    @subjects = Subject.all
  end

  # GET /subjects/1
  # GET /subjects/1.json
  def show
  end

  # GET /subjects/new
  def new
    @subject = Subject.new
  end

  # GET /subjects/1/edit
  def edit
  end

  # POST /subjects
  # POST /subjects.json
  def create
    @subject = Subject.new(subject_params)

    respond_to do |format|
      if @subject.save
        format.html { redirect_to @subject, notice: 'Предмет был успешно создан.' }
        format.json { render :show, status: :created, location: @subject }
      else
        format.html { render :new }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subjects/1
  # PATCH/PUT /subjects/1.json
  def update
    respond_to do |format|
      if @subject.update(subject_params)
        format.html { redirect_to @subject, notice: 'Предмет был успешно изменен.' }
        format.json { render :show, status: :ok, location: @subject }
      else
        format.html { render :edit }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subjects/1
  # DELETE /subjects/1.json
  def destroy
    @subject.destroy
    respond_to do |format|
      format.html { redirect_to subjects_url, notice: 'Предмет был успешно удален.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subject
      @subject = Subject.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subject_params
      params.require(:subject).permit(:name, :course, :semester)
    end
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/views/subjects/_form.html.haml
-#= form_for @subject do |f|
-#  - if @subject.errors.any?
-#    #error_explanation
-#      %h2= "#{pluralize(@subject.errors.count, "error")} prohibited this subject from being saved:"
-#      %ul
-#        - @subject.errors.full_messages.each do |msg|
-#          %li= msg
-#
-#  .field
-#    = f.label :name
-#    = f.text_field :name
-#  .field
-#    = f.label :course
-#    = f.number_field :course
-#  .field
-#    = f.label :semester
-#    = f.number_field :semester
-#  .actions
-#    = f.submit 'Save'
-#


-if session[:user] != 'stud1' and session[:user] != 'stud2'
  = form_for @subject do |f|
    =error_messages_for @subject
    .form-group
      =f.label :name
      =f.text_field :name, class: 'form-control'
    .form-group
      =f.label :course
      =f.number_field :course
    .form-group
      =f.label :semester
      =f.number_field :semester

    -#%li{class: ('active' if controller_name=='genres')}=link_to "Жанры",markdown_preview_url

    .form-actions
    = f.submit nil, class: 'btn btn-primary'
-else
  %h1
    Не доступно

app/views/subjects/edit.html.haml
%h1 Редактирование предмета

= render 'form'

= link_to 'Просмотр', @subject,class: 'btn btn-primary'
\|
= link_to 'Назад', subjects_path,class: 'btn btn-primary'

app/views/subjects/index.html.haml
-#%h1 Listing subjects
-#
-#%table
-#  %tr
-#    %th Name
-#    %th Course
-#    %th Semester
-#    %th
-#    %th
-#    %th
-#
-#  - @subjects.each do |subject|
-#    %tr
-#      %td= subject.name
-#      %td= subject.course
-#      %td= subject.semester
-#      %td= link_to 'Show', subject
-#      %td= link_to 'Edit', edit_subject_path(subject)
-#      %td= link_to 'Destroy', subject, :method => :delete, :data => { :confirm => 'Are you sure?' }
-#
-#%br
-#
-#= link_to 'New Subject', new_subject_path

%h1 Список тем

%table.table
  %tr
    %th= Subject.human_attribute_name(:name)
    %th= Subject.human_attribute_name(:course)
    %th= Subject.human_attribute_name(:semester)
    %th
    %th
    %th

  - @subjects.each do |subject|
    %tr
      %td= subject.name
      %td= subject.course
      %td= subject.semester
      %td
        = link_to 'Показать', subject
      %td
        -if session[:user] == 'tutor'
          = link_to 'Изменить', edit_subject_path(subject)
      %td
        -if session[:user] == 'tutor'
          = link_to 'Удалить', subject, :method => :delete, :data => { :confirm => 'Вы уверены?' }

%br

-if session[:user] == 'tutor'
  = link_to 'Добавить предмет', new_subject_path

app/views/subjects/new.html.haml
%h1 Новый предмет

= render 'form'

= link_to 'Назад', subjects_path,class: 'btn btn-primary'

app/views/subjects/show.html.haml
-#%p#notice= notice
-#
-#%p
-#  %b Name:
-#  = @subject.name
-#%p
-#  %b Course:
-#  = @subject.course
-#%p
-#  %b Semester:
-#  = @subject.semester
-#
-#= link_to 'Edit', edit_subject_path(@subject)
-#\|
-#= link_to 'Back', subjects_path




%p
  %b=Subject.human_attribute_name(:name)
  = @subject.name
%p
  %b=Subject.human_attribute_name(:course)
  = @subject.course
%p
  %b=Subject.human_attribute_name(:semester)
  = @subject.semester

= link_to 'Редактирование', edit_subject_path(@subject),class: 'btn btn-primary'
\|
= link_to 'Назад', subjects_path,class: 'btn btn-primary'