config/routes.rb
Rails.application.routes.draw do
  resources :topics

  resources :subjects

  resources :tests

  resources :users

  root 'tests#index'

  get 'login'=>'sessions#new', as: :login
  post 'login'=>'sessions#create'
  get 'logout'=>'sessions#destroy', as: :logout

  post "markdown/preview"
end

app/views/layouts/_error_messages_for.html.haml
-if object.errors.any?
  .panel.panel-danger
    .panel-heading
      При сохранении произошли ошибки
    .panel-body
      %ol
        -object.errors.full_messages.each do |msg|
          %li=msg

app/views/layouts/_flash_messages.html.haml
-flash.each do |key,value|
  .alert{class: "alert-#{key}"}=value

app/views/layouts/_topbar.html.haml
.navbar.navbar-default
  .container
    .navbar-header
      =link_to "Предметы", subjects_path, class: 'navbar-brand'
      =link_to "Темы", topics_path, class: 'navbar-brand'
      =link_to "Тесты", tests_path, class: 'navbar-brand'
    %ul.nav.navbar-nav

      -if session[:user] == 'admin'
        %li{class: ('active' if controller_name=='users')}=link_to "Пользователи",users_path
  -if session[:user] == 'admin'
    %ul.nav.navbar-nav.navbar-right
      -if @current_user
        %li.dropdown
          =link_to ?#,class: 'dropdown-toggle', data: {toggle: 'dropdown'} do
            =@current_user.name
            %span.caret
          %ul.dropdown-menu
            %li=link_to 'Выход',logout_path
      -else
        -#%li=link_to "Вход",login_path
        -#%li=link_to "Регистрация",new_user_path

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title
      Edu-online
    %meta{charset: 'utf-8'}
    %meta{name: 'viewport', content: "width=device-width, initial-scale=1.0"}
    = stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
  %body
    #wrap
      - if params[:action] != 'show'
        .navbar
          .container
            .navbar-brand2
              = link_to root_path, class: 'brand' do
                Institute Control Engineering and Information Technology.
                Stud-online
      .container.main
        -if session[:user] != 'stud1' and session[:user] != 'stud2'
          = render 'layouts/topbar'

        = render 'layouts/flash_messages'
        = yield

    -#- if params[:action] != 'show'
    -#  %footer#footer
    -#    = render 'layouts/footer'